-- Supabase SQL Table Setup for Call Logs
-- Paste this into your Supabase SQL Editor and click 'Run'

CREATE TABLE call_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    phone_number text,
    duration_seconds integer,
    transcript text,
    summary text
);

-- Optional: Enable Row Level Security (RLS) if you plan to expose the DB to the frontend directly.
ALTER TABLE call_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all actions for service role" ON call_logs FOR ALL USING (true);
